USE QLThuVien;

CREATE TABLE DOCGIA (
    MaDG INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    TrangThai ENUM('HoatDong', 'Khoa') NOT NULL DEFAULT 'HoatDong'
);

CREATE TABLE SACH (
    MaSach INT AUTO_INCREMENT PRIMARY KEY,
    TenSach VARCHAR(200) NOT NULL,
    SoLuong INT NOT NULL DEFAULT 0,
    SoLuongCon INT NOT NULL DEFAULT 0
);

CREATE TABLE PHIEUMUON (
    MaPM INT AUTO_INCREMENT PRIMARY KEY,
    MaDG INT NOT NULL,
    NgayMuon DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TrangThai ENUM('DangMuon', 'DaTra') NOT NULL DEFAULT 'DangMuon',

    CONSTRAINT FK_PHIEUMUON_DOCGIA
        FOREIGN KEY (MaDG)
        REFERENCES DOCGIA(MaDG)
);

CREATE TABLE CT_PHIEUMUON (
    MaPM INT NOT NULL,
    MaSach INT NOT NULL,
    HanTra DATE NOT NULL,

    PRIMARY KEY (MaPM, MaSach),

    CONSTRAINT FK_CT_PHIEUMUON_PHIEUMUON
        FOREIGN KEY (MaPM)
        REFERENCES PHIEUMUON(MaPM),

    CONSTRAINT FK_CT_PHIEUMUON_SACH
        FOREIGN KEY (MaSach)
        REFERENCES SACH(MaSach)
);